### ISSUE TITLE
Check and correct tracing after fee currency addition

### ISSUE THREAD

**Issue by palango** [celo-org/op-geth#69]
Part of [celo-org/optimism#6 ](https://github.com/celo-org/op-geth/issues/130)

- ~~One test was removed in [d694fb7defc907ad269d0a179c1d2168c2fabfbd](https://github.com/celo-org/op-geth/pull/28/commits/d694fb7defc907ad269d0a179c1d2168c2fabfbd) , because of a bug in the test setup. This also exists in upstream geth, and should be reported there.~~ Test is fixed in a proper way in https://github.com/celo-org/op-geth/commit/c66ca8bf7a8c63ae54e44f4566e206cd1a4fa204#diff-13c76087ba15a5cdb7f3003416a918dd7269b3fac232fc98908d8be927fed6d9.
- See also https://github.com/celo-org/celo-blockchain-planning/issues/66

**Comment by karlb** [comment]
Without further modifications, we currently see the following issues when tracing fee currency txs:
* Call tracer: the tracer only supports a single top level call. Calling `creditGasFees` after the main tx overwrites the trace.
* Prestate tracer: the tracing is initialized after the debit and the tracer tries to undo this by adding the debit amount back to the tx sender's account. When using fee currencies, this adds the amount to the native balance, although it has been debited from the fee currency

The problems with the prestate tracer can only be fixed by initializing the tracing earlier, since there is not safe generic way to undo the debit. The [major tracing changes in geth 1.14](https://github.com/ethereum/go-ethereum/blob/master/core/tracing/CHANGELOG.md#v1140) will help with this but are not yet included in op-geth ([update PR](https://github.com/ethereum-optimism/op-geth/pull/349)). Since waiting for these changes should make a proper solution for the prestate tracer possible and will reduce rebasing work, I suggest to delay implementing this.

Some commits I collected while experimenting can be found at https://github.com/celo-org/op-geth/compare/celo7...celo-org:op-geth:karlb/tracing-stash?expand=1.

**Comment by karlb** [comment]
But we can already collect some thoughts on how these tracers should work.

## Call tracer

Usually, debiting and crediting does not show up in the call trace, since no calls are used in the process. With fee currencies, two calls are used in addition to the main tx call. I assume that most users will expect the same call trace result no matter how the fees are paid. Therefore, tracing should be disabled for debiting and crediting by default.

We could provide a special fee currency call tracer that includes debit and credit and returns three top level calls. It is unclear if there is any demand for this and whether people will find out how to enable non-standard tracers. Thoughts?

## Prestate tracer

The prestate tracer's result must be sufficient to execute the traced tx. This only works if
* we include the debit (and probably credit) in the trace. Otherwise, we would miss the fee currency contract code and state.
* we include the required exchange rate as a special field in the pre state. The exchange rates won't show up in the trace because they are read once per block outside of the tx execution.
* we capture the pre state balance correctly before the debit is made
